# Generated by Django 6.0 on 2025-12-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(default='', max_length=150)),
                ('name_en', models.CharField(default='', max_length=150)),
                ('name_ar', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=255, unique=True)),
                ('short_description_fa', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_ar', models.TextField(blank=True, null=True)),
                ('description_fa', models.TextField(blank=True, default='', null=True)),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('description_ar', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_text_fa', models.TextField(default='')),
                ('shipping_text_en', models.TextField(default='')),
                ('shipping_text_ar', models.TextField(default='')),
                ('return_text_fa', models.TextField(default='')),
                ('return_text_en', models.TextField(default='')),
                ('return_text_ar', models.TextField(default='')),
                ('packaging_text_fa', models.TextField(default='')),
                ('packaging_text_en', models.TextField(default='')),
                ('packaging_text_ar', models.TextField(default='')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(default='', max_length=100)),
                ('title_en', models.CharField(default='', max_length=100)),
                ('title_ar', models.CharField(default='', max_length=100)),
                ('value_fa', models.CharField(default='', max_length=255)),
                ('value_en', models.CharField(default='', max_length=255)),
                ('value_ar', models.CharField(default='', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_fa', models.CharField(default='', max_length=50)),
                ('label_en', models.CharField(default='', max_length=50)),
                ('label_ar', models.CharField(default='', max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
