# Generated by Django 6.0 on 2025-12-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
