# Generated by Django 6.0 on 2026-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Wating for payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('shipped', 'Product is Shipped'), ('canceled', 'Product got Canceled'), ('processing', 'Product is in Processing'), ('delivered', 'Product is Delivered')], default='pending', max_length=20),
        ),
    ]
